//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.DataAccess
{
    using ASI.MGC.FS.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASI_MGC_FSEntities : DbContext
    {
        public ASI_MGC_FSEntities()
            : base("name=ASI_MGC_FSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACSTATEMENT_RPT> ACSTATEMENT_RPT { get; set; }
        public virtual DbSet<ALLOCATIONMASTER> ALLOCATIONMASTERs { get; set; }
        public virtual DbSet<AR_AP_LEDGER> AR_AP_LEDGER { get; set; }
        public virtual DbSet<AR_AP_MASTER> AR_AP_MASTER { get; set; }
        public virtual DbSet<ARMATCHING> ARMATCHINGs { get; set; }
        public virtual DbSet<BALANCESHEET> BALANCESHEETs { get; set; }
        public virtual DbSet<BANKMASTER> BANKMASTERs { get; set; }
        public virtual DbSet<BANKMASTER1> BANKMASTER1 { get; set; }
        public virtual DbSet<BANKTRANSACTION> BANKTRANSACTIONs { get; set; }
        public virtual DbSet<COMPANYMASTER> COMPANYMASTERs { get; set; }
        public virtual DbSet<CUSTOMEREPORT> CUSTOMEREPORTs { get; set; }
        public virtual DbSet<DELEVERYNOTE> DELEVERYNOTEs { get; set; }
        public virtual DbSet<DELEVERYNOTE_RPT> DELEVERYNOTE_RPT { get; set; }
        public virtual DbSet<DELREPORT_MASTER> DELREPORT_MASTER { get; set; }
        public virtual DbSet<DOCCUMENTMASTER> DOCCUMENTMASTERs { get; set; }
        public virtual DbSet<EMPLOYEEMASTER> EMPLOYEEMASTERs { get; set; }
        public virtual DbSet<ENTRYMASTER> ENTRYMASTERs { get; set; }
        public virtual DbSet<FINYEARMASTER> FINYEARMASTERs { get; set; }
        public virtual DbSet<GLMASTER> GLMASTERs { get; set; }
        public virtual DbSet<GLTRANSACTION1> GLTRANSACTION1 { get; set; }
        public virtual DbSet<INVDETAIL> INVDETAILS { get; set; }
        public virtual DbSet<INVMASTER> INVMASTERs { get; set; }
        public virtual DbSet<JOB_REPORT> JOB_REPORT { get; set; }
        public virtual DbSet<JOBCARD_REPRT> JOBCARD_REPRT { get; set; }
        public virtual DbSet<JOBDETAL> JOBDETALS { get; set; }
        public virtual DbSet<JOBIDREFERENCE> JOBIDREFERENCEs { get; set; }
        public virtual DbSet<JOBMASTER> JOBMASTERs { get; set; }
        public virtual DbSet<JVREPORT> JVREPORTs { get; set; }
        public virtual DbSet<LOCATIONMASTER> LOCATIONMASTERs { get; set; }
        public virtual DbSet<MATERIALRECEIPTMASTER> MATERIALRECEIPTMASTERs { get; set; }
        public virtual DbSet<MRV_REPORT_CHD> MRV_REPORT_CHD { get; set; }
        public virtual DbSet<MRVNO_REPORT> MRVNO_REPORT { get; set; }
        public virtual DbSet<MRVREFERENCE> MRVREFERENCEs { get; set; }
        public virtual DbSet<PANDL_SETTINGS> PANDL_SETTINGS { get; set; }
        public virtual DbSet<PRODUCTMASTER> PRODUCTMASTERs { get; set; }
        public virtual DbSet<PROFITANDLOSS_RPT> PROFITANDLOSS_RPT { get; set; }
        public virtual DbSet<QOTATION_REF> QOTATION_REF { get; set; }
        public virtual DbSet<QUOT_PROD_MASTER> QUOT_PROD_MASTER { get; set; }
        public virtual DbSet<QUOTATION_MASTER> QUOTATION_MASTER { get; set; }
        public virtual DbSet<REPORT_JOBCARD> REPORT_JOBCARD { get; set; }
        public virtual DbSet<SALEDETAIL> SALEDETAILS { get; set; }
        public virtual DbSet<SALESALLOCATIONMASTER> SALESALLOCATIONMASTERs { get; set; }
        public virtual DbSet<SALESMASTER> SALESMASTERs { get; set; }
        public virtual DbSet<SLNOGENERATOR> SLNOGENERATORs { get; set; }
        public virtual DbSet<STOCK_REPORT> STOCK_REPORT { get; set; }
        public virtual DbSet<STOCKLEDGER> STOCKLEDGERs { get; set; }
        public virtual DbSet<STOCKLEDGER_REPORT> STOCKLEDGER_REPORT { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TELEPHONE_DIRECTORY> TELEPHONE_DIRECTORY { get; set; }
        public virtual DbSet<TEMPREPORT> TEMPREPORTs { get; set; }
        public virtual DbSet<TRIALBALANCE> TRIALBALANCEs { get; set; }
        public virtual DbSet<UNITMESSUREMENT> UNITMESSUREMENTs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VOUCHERCHILD_RPT> VOUCHERCHILD_RPT { get; set; }
        public virtual DbSet<VOUCHERMASTER_RPT> VOUCHERMASTER_RPT { get; set; }
    }
}
