//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACSTATEMENT_RPT
    {
        public int SLNO_SAC { get; set; }
        public string ACCODE_SAC { get; set; }
        public Nullable<System.DateTime> GLDATE_SAC { get; set; }
        public string DOCNUMBER_SAC { get; set; }
        public string OTHERREF_SAC { get; set; }
        public string NARRATION_SAC { get; set; }
        public Nullable<decimal> DEBITAMOUNT_SAC { get; set; }
        public Nullable<decimal> CREDITAMOUNT_SAC { get; set; }
        public Nullable<decimal> BALANCE_SAC { get; set; }
        public string USER_SAC { get; set; }
    }
}
