//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_AP_MASTER
    {
        public string ARCODE_ARM { get; set; }
        public string TYPE_ARM { get; set; }
        public string DESCRIPTION_ARM { get; set; }
        public string POBOX_ARM { get; set; }
        public string ADDRESS1_ARM { get; set; }
        public string ADDRESS2_ARM { get; set; }
        public string ADDRESS3_ARM { get; set; }
        public string TELEPHONE_ARM { get; set; }
        public string FAX_ARM { get; set; }
        public string EMAIL_ARM { get; set; }
        public string CONDACTPERSON_ARM { get; set; }
        public string SALESEXE_ARM { get; set; }
        public string RECEIVABLETYPE_ARM { get; set; }
        public string STATUS_ARM { get; set; }
        public Nullable<decimal> LIMITAMOUNT_ARM { get; set; }
        public Nullable<int> CREDITDAYS_ARM { get; set; }
    }
}
