//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_AP_LEDGER
    {
        public int SlNo_ART { get; set; }
        public string DOCNUMBER_ART { get; set; }
        public Nullable<System.DateTime> DODATE_ART { get; set; }
        public Nullable<System.DateTime> GLDATE_ART { get; set; }
        public string ARAPCODE_ART { get; set; }
        public Nullable<decimal> DEBITAMOUNT_ART { get; set; }
        public Nullable<decimal> CREDITAMOUNT_ART { get; set; }
        public string OTHERREF_ART { get; set; }
        public string NARRATION_ART { get; set; }
        public string USER_ART { get; set; }
        public Nullable<decimal> MATCHVALUE_AR { get; set; }
        public string STATUS_ART { get; set; }
        public Nullable<decimal> VAT_ART { get; set; }
    }
}
