//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMATCHING
    {
        public int SLNO { get; set; }
        public string DOCCNUMBER_ARM { get; set; }
        public string MACHTNUMBER_ARM { get; set; }
        public Nullable<int> AMOUNT_ARM { get; set; }
        public string USER_ARM { get; set; }
        public string ACCODE_ARM { get; set; }
        public Nullable<int> MATCHNO_ARM { get; set; }
    }
}
