//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASI_MGC_FSEntities : DbContext
    {
        public ASI_MGC_FSEntities()
            : base("name=ASI_MGC_FSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACSTATEMENT_RPT> ACSTATEMENT_RPT { get; set; }
        public virtual DbSet<ALLOCATIONMASTER> ALLOCATIONMASTERs { get; set; }
        public virtual DbSet<AR_AP_LEDGER> AR_AP_LEDGER { get; set; }
        public virtual DbSet<AR_AP_MASTER> AR_AP_MASTER { get; set; }
        public virtual DbSet<ARMATCHING> ARMATCHINGs { get; set; }
        public virtual DbSet<BALANCESHEET> BALANCESHEETs { get; set; }
        public virtual DbSet<BANKMASTER> BANKMASTERs { get; set; }
        public virtual DbSet<BANKMASTER1> BANKMASTER1 { get; set; }
        public virtual DbSet<BANKTRANSACTION> BANKTRANSACTIONs { get; set; }
        public virtual DbSet<COMPANYMASTER> COMPANYMASTERs { get; set; }
        public virtual DbSet<CUSTOMEREPORT> CUSTOMEREPORTs { get; set; }
        public virtual DbSet<DELEVERYNOTE> DELEVERYNOTEs { get; set; }
        public virtual DbSet<DELEVERYNOTE_RPT> DELEVERYNOTE_RPT { get; set; }
        public virtual DbSet<DELREPORT_MASTER> DELREPORT_MASTER { get; set; }
        public virtual DbSet<DOCCUMENTMASTER> DOCCUMENTMASTERs { get; set; }
        public virtual DbSet<EMPLOYEEMASTER> EMPLOYEEMASTERs { get; set; }
        public virtual DbSet<ENTRYMASTER> ENTRYMASTERs { get; set; }
        public virtual DbSet<FINYEARMASTER> FINYEARMASTERs { get; set; }
        public virtual DbSet<GLMASTER> GLMASTERs { get; set; }
        public virtual DbSet<GLTRANSACTION1> GLTRANSACTION1 { get; set; }
        public virtual DbSet<INVDETAIL> INVDETAILS { get; set; }
        public virtual DbSet<INVMASTER> INVMASTERs { get; set; }
        public virtual DbSet<JOB_REPORT> JOB_REPORT { get; set; }
        public virtual DbSet<JOBCARD_REPRT> JOBCARD_REPRT { get; set; }
        public virtual DbSet<JOBDETAL> JOBDETALS { get; set; }
        public virtual DbSet<JOBIDREFERENCE> JOBIDREFERENCEs { get; set; }
        public virtual DbSet<JOBMASTER> JOBMASTERs { get; set; }
        public virtual DbSet<JVREPORT> JVREPORTs { get; set; }
        public virtual DbSet<LOCATIONMASTER> LOCATIONMASTERs { get; set; }
        public virtual DbSet<MATERIALRECEIPTMASTER> MATERIALRECEIPTMASTERs { get; set; }
        public virtual DbSet<MRV_REPORT_CHD> MRV_REPORT_CHD { get; set; }
        public virtual DbSet<MRVNO_REPORT> MRVNO_REPORT { get; set; }
        public virtual DbSet<MRVREFERENCE> MRVREFERENCEs { get; set; }
        public virtual DbSet<PANDL_SETTINGS> PANDL_SETTINGS { get; set; }
        public virtual DbSet<PRODUCTMASTER> PRODUCTMASTERs { get; set; }
        public virtual DbSet<PROFITANDLOSS_RPT> PROFITANDLOSS_RPT { get; set; }
        public virtual DbSet<QOTATION_REF> QOTATION_REF { get; set; }
        public virtual DbSet<QUOT_PROD_MASTER> QUOT_PROD_MASTER { get; set; }
        public virtual DbSet<QUOTATION_MASTER> QUOTATION_MASTER { get; set; }
        public virtual DbSet<REPORT_JOBCARD> REPORT_JOBCARD { get; set; }
        public virtual DbSet<SALEDETAIL> SALEDETAILS { get; set; }
        public virtual DbSet<SALESALLOCATIONMASTER> SALESALLOCATIONMASTERs { get; set; }
        public virtual DbSet<SALESMASTER> SALESMASTERs { get; set; }
        public virtual DbSet<SLNOGENERATOR> SLNOGENERATORs { get; set; }
        public virtual DbSet<STOCK_REPORT> STOCK_REPORT { get; set; }
        public virtual DbSet<STOCKLEDGER> STOCKLEDGERs { get; set; }
        public virtual DbSet<STOCKLEDGER_REPORT> STOCKLEDGER_REPORT { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TELEPHONE_DIRECTORY> TELEPHONE_DIRECTORY { get; set; }
        public virtual DbSet<TEMPREPORT> TEMPREPORTs { get; set; }
        public virtual DbSet<TRIALBALANCE> TRIALBALANCEs { get; set; }
        public virtual DbSet<UNITMESSUREMENT> UNITMESSUREMENTs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VOUCHERCHILD_RPT> VOUCHERCHILD_RPT { get; set; }
        public virtual DbSet<VOUCHERMASTER_RPT> VOUCHERMASTER_RPT { get; set; }
        public virtual DbSet<MESRole> MESRoles { get; set; }
        public virtual DbSet<MESUser> MESUsers { get; set; }
        public virtual DbSet<MESUserLoginDetail> MESUserLoginDetails { get; set; }
        public virtual DbSet<MESUserProfile> MESUserProfiles { get; set; }
        public virtual DbSet<MESUserRole> MESUserRoles { get; set; }
    
        public virtual ObjectResult<rpt_BankPayment_Result> rpt_BankPayment(string vTYPE, string vCODE)
        {
            var vTYPEParameter = vTYPE != null ?
                new ObjectParameter("VTYPE", vTYPE) :
                new ObjectParameter("VTYPE", typeof(string));
    
            var vCODEParameter = vCODE != null ?
                new ObjectParameter("VCODE", vCODE) :
                new ObjectParameter("VCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_BankPayment_Result>("rpt_BankPayment", vTYPEParameter, vCODEParameter);
        }
    
        public virtual ObjectResult<rpt_BankReceipt_Result> rpt_BankReceipt(string vTYPE, string vCODE)
        {
            var vTYPEParameter = vTYPE != null ?
                new ObjectParameter("VTYPE", vTYPE) :
                new ObjectParameter("VTYPE", typeof(string));
    
            var vCODEParameter = vCODE != null ?
                new ObjectParameter("VCODE", vCODE) :
                new ObjectParameter("VCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_BankReceipt_Result>("rpt_BankReceipt", vTYPEParameter, vCODEParameter);
        }
    
        public virtual ObjectResult<rpt_CashPayment_Result> rpt_CashPayment(string vTYPE, string vCODE)
        {
            var vTYPEParameter = vTYPE != null ?
                new ObjectParameter("VTYPE", vTYPE) :
                new ObjectParameter("VTYPE", typeof(string));
    
            var vCODEParameter = vCODE != null ?
                new ObjectParameter("VCODE", vCODE) :
                new ObjectParameter("VCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_CashPayment_Result>("rpt_CashPayment", vTYPEParameter, vCODEParameter);
        }
    
        public virtual ObjectResult<rpt_CashReceipt_Result> rpt_CashReceipt(string vTYPE, string vCODE)
        {
            var vTYPEParameter = vTYPE != null ?
                new ObjectParameter("VTYPE", vTYPE) :
                new ObjectParameter("VTYPE", typeof(string));
    
            var vCODEParameter = vCODE != null ?
                new ObjectParameter("VCODE", vCODE) :
                new ObjectParameter("VCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_CashReceipt_Result>("rpt_CashReceipt", vTYPEParameter, vCODEParameter);
        }
    
        public virtual ObjectResult<rpt_CashMemo_Result> rpt_CashMemo(string iNVNO, string iNVTYPE)
        {
            var iNVNOParameter = iNVNO != null ?
                new ObjectParameter("INVNO", iNVNO) :
                new ObjectParameter("INVNO", typeof(string));
    
            var iNVTYPEParameter = iNVTYPE != null ?
                new ObjectParameter("INVTYPE", iNVTYPE) :
                new ObjectParameter("INVTYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_CashMemo_Result>("rpt_CashMemo", iNVNOParameter, iNVTYPEParameter);
        }
    
        public virtual ObjectResult<rpt_CompanyDetails_Result> rpt_CompanyDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_CompanyDetails_Result>("rpt_CompanyDetails");
        }
    
        public virtual ObjectResult<rpt_DeliveryNote_Result> rpt_DeliveryNote(string dLNO, string dLNTYPE)
        {
            var dLNOParameter = dLNO != null ?
                new ObjectParameter("DLNO", dLNO) :
                new ObjectParameter("DLNO", typeof(string));
    
            var dLNTYPEParameter = dLNTYPE != null ?
                new ObjectParameter("DLNTYPE", dLNTYPE) :
                new ObjectParameter("DLNTYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_DeliveryNote_Result>("rpt_DeliveryNote", dLNOParameter, dLNTYPEParameter);
        }
    
        public virtual ObjectResult<rpt_Invoice_Result> rpt_Invoice(string iNV_NO, string iNVTYPE)
        {
            var iNV_NOParameter = iNV_NO != null ?
                new ObjectParameter("INV_NO", iNV_NO) :
                new ObjectParameter("INV_NO", typeof(string));
    
            var iNVTYPEParameter = iNVTYPE != null ?
                new ObjectParameter("INVTYPE", iNVTYPE) :
                new ObjectParameter("INVTYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_Invoice_Result>("rpt_Invoice", iNV_NOParameter, iNVTYPEParameter);
        }
    
        public virtual ObjectResult<rpt_JobCardFormat_Result> rpt_JobCardFormat(string jOBNO)
        {
            var jOBNOParameter = jOBNO != null ?
                new ObjectParameter("JOBNO", jOBNO) :
                new ObjectParameter("JOBNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_JobCardFormat_Result>("rpt_JobCardFormat", jOBNOParameter);
        }
    
        public virtual ObjectResult<rpt_MaterialReceiptVcoucher_Result> rpt_MaterialReceiptVcoucher(string mRVNO)
        {
            var mRVNOParameter = mRVNO != null ?
                new ObjectParameter("MRVNO", mRVNO) :
                new ObjectParameter("MRVNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_MaterialReceiptVcoucher_Result>("rpt_MaterialReceiptVcoucher", mRVNOParameter);
        }
    
        public virtual ObjectResult<rpt_Quotation_Result> rpt_Quotation(string quotNo)
        {
            var quotNoParameter = quotNo != null ?
                new ObjectParameter("QuotNo", quotNo) :
                new ObjectParameter("QuotNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_Quotation_Result>("rpt_Quotation", quotNoParameter);
        }
    }
}
