//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALANCESHEET
    {
        public int SLNO_BS { get; set; }
        public string MAINCODE_BS { get; set; }
        public string ACCODE_BS { get; set; }
        public string SUBDESCRIPTION_BS { get; set; }
        public string ACDESCRIPTION_BS { get; set; }
        public Nullable<decimal> AMOUNT_BS { get; set; }
        public Nullable<decimal> AMOUNT2_BS { get; set; }
    }
}
