//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKTRANSACTION
    {
        public int SLNo_BT { get; set; }
        public string DOCNUMBER_BT { get; set; }
        public string BANKCODE_BT { get; set; }
        public Nullable<System.DateTime> DOCDATE_BT { get; set; }
        public Nullable<System.DateTime> GLDATE_BT { get; set; }
        public Nullable<decimal> DEBITAMOUT_BT { get; set; }
        public Nullable<decimal> CREDITAMOUT_BT { get; set; }
        public string OTHERREF_BT { get; set; }
        public string CHQNO_BT { get; set; }
        public Nullable<System.DateTime> CHQDATE_BT { get; set; }
        public Nullable<System.DateTime> CLEARANCEDATE_BT { get; set; }
        public string BENACNO_BT { get; set; }
        public string BENACCOUNT_BT { get; set; }
        public string NARRATION_BT { get; set; }
        public string NOTE_BT { get; set; }
        public string STATUS_BT { get; set; }
        public string USER_BT { get; set; }
        public string MASTERSTATUS_BT { get; set; }
        public Nullable<decimal> VAT_BT { get; set; }
    
        public virtual BANKMASTER BANKMASTER { get; set; }
    }
}
