//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKMASTER
    {
        public BANKMASTER()
        {
            this.BANKTRANSACTIONs = new HashSet<BANKTRANSACTION>();
        }
    
        public string BANKCODE_BM { get; set; }
        public string BANKNAME_BM { get; set; }
        public string CURRENCY_BM { get; set; }
        public string ACCOUNTNUMBER_BM { get; set; }
        public string BANKSTTUS_BM { get; set; }
        public Nullable<decimal> ODLIMIT_BM { get; set; }
        public string MODE_BM { get; set; }
        public string RECEIPTLOCATION_BM { get; set; }
    
        public virtual ICollection<BANKTRANSACTION> BANKTRANSACTIONs { get; set; }
    }
}
