//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANYMASTER
    {
        public string COCODE_CM { get; set; }
        public string COMPANYNAME_CM { get; set; }
        public string PBNO_CM { get; set; }
        public string ARRRESS1_CM { get; set; }
        public string ADDRESS2_CM { get; set; }
        public string ADDRESS3_CM { get; set; }
        public string PHONENO_CM { get; set; }
        public string FAXNUMBER_CM { get; set; }
        public string TELEXNO_CM { get; set; }
        public string EMAIL_CM { get; set; }
        public string GROUPCODE { get; set; }
        public Nullable<int> DECIMALPOINTS_CM { get; set; }
        public string BASECURRENCY_CM { get; set; }
        public string CURRECNCYNAME_CM { get; set; }
        public string PERRIODMETHOD_CM { get; set; }
        public string LOGOPATH_CM { get; set; }
    }
}
