//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELEVERYNOTE
    {
        public int SLNO_DL { get; set; }
        public string PRCODE_DL { get; set; }
        public string PRNAME_DL { get; set; }
        public string DELNO_DL { get; set; }
        public string MRVNO_DL { get; set; }
    }
}
