//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELEVERYNOTE_RPT
    {
        public int SLNO_DLNRPT { get; set; }
        public string DLNR_DLNRPT { get; set; }
        public string ID_DLNRPT { get; set; }
        public string DESCRIPTION_DLNRPT { get; set; }
        public Nullable<int> QTY_DLNRPT { get; set; }
        public string JOBNO_DLNRPT { get; set; }
        public string SERVICEPROID_DLNRPT { get; set; }
        public string DLNTYPE_DLNRPT { get; set; }
    }
}
