//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCCUMENTMASTER
    {
        public string DOCTYPE_DM { get; set; }
        public string DESCRIPTION_DM { get; set; }
        public string DOCABBREVIATION_DM { get; set; }
        public Nullable<bool> ARSTATUS_DM { get; set; }
        public Nullable<bool> APSTATUS_DM { get; set; }
        public Nullable<bool> GLSTATUS_DM { get; set; }
        public Nullable<bool> BANKSTATUS_DM { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
