//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEMASTER
    {
        public string EMPCODE_EM { get; set; }
        public string EMPFNAME_EM { get; set; }
        public string EMPSNAME_EM { get; set; }
        public string PASSPORTNO_EM { get; set; }
        public string PHONE_EM { get; set; }
        public string DESIGNATION_EM { get; set; }
        public Nullable<System.DateTime> PASSPORTISSUEDATE_EM { get; set; }
        public Nullable<System.DateTime> PASSPORTEXPDATE_EM { get; set; }
        public Nullable<System.DateTime> VISAISSUEDATE_EM { get; set; }
        public Nullable<System.DateTime> VISAEXPIEARYDATE_EM { get; set; }
    }
}
