//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRYMASTER
    {
        public string ENTRYCODE_EM { get; set; }
        public string ACCODE_EM { get; set; }
        public string DESCRIPTION_EM { get; set; }
    }
}
