//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINYEARMASTER
    {
        public System.DateTime PERRIEDFROM_FM { get; set; }
        public Nullable<System.DateTime> PERRIEDRTO_FM { get; set; }
        public Nullable<bool> GLSTATUS_FM { get; set; }
        public Nullable<bool> BANKSTATUS_FM { get; set; }
        public Nullable<bool> ARAPSTATUS_FM { get; set; }
        public Nullable<bool> CURRENTPERIOD_FM { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
