//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLMASTER
    {
        public string GLCODE_LM { get; set; }
        public string GLDESCRIPTION_LM { get; set; }
        public string LOCATIONCODE_LM { get; set; }
        public string MAINCODE_LM { get; set; }
        public string SUBCODE_LM { get; set; }
        public string GTYPE_LM { get; set; }
        public string NOTES_LM { get; set; }
    }
}
