//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLTRANSACTION1
    {
        public int SLNO_GLT { get; set; }
        public string DOCNUMBER_GLT { get; set; }
        public Nullable<System.DateTime> DOCDATE_GLT { get; set; }
        public Nullable<System.DateTime> GLDATE_GLT { get; set; }
        public string GLACCODE_GLT { get; set; }
        public string OTHERREF_GLT { get; set; }
        public Nullable<decimal> DEBITAMOUNT_GLT { get; set; }
        public Nullable<decimal> CREDITAMOUNT_GLT { get; set; }
        public string NARRATION_GLT { get; set; }
        public string GLSTATUS_GLT { get; set; }
        public string VARUSER { get; set; }
    }
}
