//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVDETAIL
    {
        public int SLNO_INVD { get; set; }
        public string CODE_INVD { get; set; }
        public string DESCRIPTION_INVD { get; set; }
        public Nullable<int> QTY_INVD { get; set; }
        public Nullable<decimal> RATE_INVD { get; set; }
        public Nullable<decimal> AMOUNT_INVNO { get; set; }
        public string INVNO_INVD { get; set; }
        public string JOBNO_INVD { get; set; }
        public string UNIT_INVD { get; set; }
    }
}
