//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVMASTER
    {
        public string INVNO_IPM { get; set; }
        public Nullable<System.DateTime> INVDATE_IPM { get; set; }
        public string CUST_CODE_IPM { get; set; }
        public string CUSTNAME_IPM { get; set; }
        public string CUSTADDRESS_IPM { get; set; }
        public string CUSTPIN_IPM { get; set; }
        public Nullable<decimal> SHIPPING_IPM { get; set; }
        public Nullable<decimal> DISCOUNT_IPM { get; set; }
        public string LPONO_IPM { get; set; }
        public string SALESFIGURE_IPM { get; set; }
    }
}
