//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_REPORT
    {
        public int SLNO_JR { get; set; }
        public string JOBNO_JR { get; set; }
        public string CODE_JR { get; set; }
        public string DESCRIPTION_JR { get; set; }
        public Nullable<int> QTY_JR { get; set; }
        public Nullable<decimal> RATE_JR { get; set; }
        public Nullable<decimal> DISCOUNT_JR { get; set; }
        public Nullable<decimal> SHIPPINGCHARGES_JR { get; set; }
        public string UNIT_JR { get; set; }
        public Nullable<decimal> VAT_JR { get; set; }
    }
}
