//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBCARD_REPRT
    {
        public string JOBNO_JRP { get; set; }
        public string MRVNO_JRP { get; set; }
        public Nullable<System.DateTime> JOBDATE_JRP { get; set; }
        public string PRODID_JRP { get; set; }
        public string PRODUCTNAME_JRP { get; set; }
    }
}
