//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDETAL
    {
        public int SLNO_JD { get; set; }
        public string JOBNO_JD { get; set; }
        public Nullable<System.DateTime> SALEDATE_JD { get; set; }
        public string PRODCODE_JD { get; set; }
        public string JOBID_JD { get; set; }
        public string ACCODE_JD { get; set; }
        public Nullable<int> QTY_JD { get; set; }
        public Nullable<decimal> RATE_JD { get; set; }
        public Nullable<decimal> AMOUNT_JD { get; set; }
        public string NOTES_JD { get; set; }
        public string STATUS_JD { get; set; }
        public string POSTDOCNO1_JD { get; set; }
        public string POSTDOCNO2_JD { get; set; }
    }
}
