//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBIDREFERENCE
    {
        public JOBIDREFERENCE()
        {
            this.MRVREFERENCEs = new HashSet<MRVREFERENCE>();
        }
    
        public string JOBID_JR { get; set; }
        public string JOBDESCRIPTION_JR { get; set; }
        public Nullable<decimal> RATE_RJ { get; set; }
    
        public virtual ICollection<MRVREFERENCE> MRVREFERENCEs { get; set; }
    }
}
