//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBMASTER
    {
        public string JOBNO_JM { get; set; }
        public Nullable<System.DateTime> DOCDATE_JM { get; set; }
        public string MRVNO_JM { get; set; }
        public string EMPCODE_JM { get; set; }
        public string JOBCODE_JM { get; set; }
        public string JOBSTATUS_JM { get; set; }
        public string DELEVERNOTENO_JM { get; set; }
        public string DOCNUMBER_JM { get; set; }
        public string PRODID_JIM { get; set; }
        public Nullable<int> PRODQTY_JM { get; set; }
        public string REMARIKS_JM { get; set; }
    
        public virtual MATERIALRECEIPTMASTER MATERIALRECEIPTMASTER { get; set; }
    }
}
