//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JVREPORT
    {
        public int SLNO_VPT { get; set; }
        public Nullable<System.DateTime> DOCDATE_VPR { get; set; }
        public Nullable<System.DateTime> GLDATE_VPR { get; set; }
        public string ALCODE_VPT { get; set; }
        public string ACCODE_VPR { get; set; }
        public string ACDESCRIPTION_VPR { get; set; }
        public Nullable<decimal> DEBITAMOUNT_VPR { get; set; }
        public Nullable<decimal> CREDITAMOUNT_VPR { get; set; }
        public string NARRATION_VPT { get; set; }
        public string DOCNO_VPT { get; set; }
    }
}
