//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESUser
    {
        public MESUser()
        {
            this.MESUserLoginDetails = new HashSet<MESUserLoginDetail>();
            this.MESUserProfiles = new HashSet<MESUserProfile>();
            this.MESUserRoles = new HashSet<MESUserRole>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<MESUserLoginDetail> MESUserLoginDetails { get; set; }
        public virtual ICollection<MESUserProfile> MESUserProfiles { get; set; }
        public virtual ICollection<MESUserRole> MESUserRoles { get; set; }
    }
}
