//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESUnAuthenticatedUsersAccess
    {
        public int ID { get; set; }
        public string UserIdentityName { get; set; }
        public string UserHostAddress { get; set; }
        public string UserHostName { get; set; }
        public string Browser { get; set; }
        public string MacAddress { get; set; }
        public bool IsMobileDevice { get; set; }
        public string MobileDeviceManufacturer { get; set; }
        public string MobileDeviceModal { get; set; }
        public string Email { get; set; }
        public bool ExistedUser { get; set; }
    }
}
