//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRV_REPORT_CHD
    {
        public int SLNO { get; set; }
        public string MRVNO_CHD { get; set; }
        public string PCODE_CHD { get; set; }
        public string PRODUCTNAME_CHD { get; set; }
        public string JOBID_CHD { get; set; }
        public string JOBDIES_CHD { get; set; }
        public Nullable<int> QTY_CHD { get; set; }
        public Nullable<decimal> RATE_CHD { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
