//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRVNO_REPORT
    {
        public string MRVNO_RPT { get; set; }
        public Nullable<System.DateTime> MRVDATE_RPT { get; set; }
        public Nullable<System.DateTime> MRVDELEDATE_RPT { get; set; }
        public string CUSTCODE_RPT { get; set; }
        public string CUSTNAME_RPT { get; set; }
        public string CUSTADD_RPT { get; set; }
        public string PHONE_RPT { get; set; }
    }
}
