//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRVREFERENCE
    {
        public int SLNO_MRR { get; set; }
        public string MRVNO_MRR { get; set; }
        public string PRODID_MRR { get; set; }
        public Nullable<int> QTY_MRR { get; set; }
        public Nullable<decimal> RATE_MRR { get; set; }
        public Nullable<decimal> AMOUNT_MRR { get; set; }
        public string JOBID_MRR { get; set; }
        public string JOBSTATUS_MRR { get; set; }
    
        public virtual JOBIDREFERENCE JOBIDREFERENCE { get; set; }
        public virtual MATERIALRECEIPTMASTER MATERIALRECEIPTMASTER { get; set; }
        public virtual PRODUCTMASTER PRODUCTMASTER { get; set; }
    }
}
