//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOGENERATOR
    {
        public int SLNO { get; set; }
        public string DOCTYPE_NG { get; set; }
        public Nullable<int> SLNO_NG { get; set; }
        public Nullable<int> FINYEAR_NG { get; set; }
    }
}
