//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QOTATION_REF
    {
        public int SLNO_QREF { get; set; }
        public string QUOTNO_QREF { get; set; }
        public string CODE_QREF { get; set; }
        public string DESCRIPTION_QREF { get; set; }
        public Nullable<int> QTY_QREF { get; set; }
        public Nullable<decimal> RATE_QREF { get; set; }
        public Nullable<int> ID_QREF { get; set; }
        public Nullable<decimal> AMOUNT_QREF { get; set; }
        public Nullable<decimal> VAT_QREF { get; set; }
    }
}
