//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATION_MASTER
    {
        public string QUOTNO_QM { get; set; }
        public string CUSTNAME_QM { get; set; }
        public string ADDRESS1_QM { get; set; }
        public string ADDRESS2_QM { get; set; }
        public string NOTE_QM { get; set; }
        public Nullable<System.DateTime> DATE_QM { get; set; }
        public Nullable<decimal> CUSTVATNO_QM { get; set; }
    }
}
