//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOT_PROD_MASTER
    {
        public int RECNO_QPRM { get; set; }
        public string QUOTNO_QPRM { get; set; }
        public string PRODID_QPRM { get; set; }
        public Nullable<int> SLNO_QPRM { get; set; }
        public Nullable<int> QTY_QPRM { get; set; }
    }
}
