//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_JOBCARD
    {
        public int SLNO_JCARD { get; set; }
        public string MRVNO_JCARD { get; set; }
        public string JOBCARDNO_JRD { get; set; }
        public Nullable<System.DateTime> JOBDATE_JCARD { get; set; }
        public string PRODID_JCARD { get; set; }
        public string PRODUCTNAME_JCARD { get; set; }
        public Nullable<System.DateTime> DELEDATE_JCARD { get; set; }
        public Nullable<int> PRODQTY_JCARD { get; set; }
        public string EMPCODE_JCARD { get; set; }
        public string EMPNAME_JCARD { get; set; }
        public string JOBID_JCARD { get; set; }
        public string JOBDESCRIPTION_JCARD { get; set; }
    }
}
