//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMASTER
    {
        public string MRVNO_SM { get; set; }
        public string CUSTCODE_SM { get; set; }
        public Nullable<System.DateTime> DOCDATE_SM { get; set; }
        public Nullable<System.DateTime> SALEDATE_SM { get; set; }
        public Nullable<decimal> DISCOUNT_SM { get; set; }
        public Nullable<decimal> SHIPPING_SM { get; set; }
        public Nullable<decimal> JOBTOTAL_SM { get; set; }
        public Nullable<decimal> PRODUCTTOTAL_SM { get; set; }
        public Nullable<decimal> CASHTOTAL_SM { get; set; }
        public Nullable<decimal> CREDITTOTAL_SM { get; set; }
        public Nullable<decimal> NETAMOUNT_SM { get; set; }
        public string STATUS_SM { get; set; }
        public string CREDITDOCNO_SM { get; set; }
        public string CASHDOCNO_SM { get; set; }
    }
}
