//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLNOGENERATOR
    {
        public int SLNO { get; set; }
        public string YEAR_SLG { get; set; }
        public string DOCABR_SLG { get; set; }
        public Nullable<int> SLNO_SLG { get; set; }
    }
}
