//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKLEDGER
    {
        public int SLNO_SL { get; set; }
        public Nullable<System.DateTime> DOC_DATE_SL { get; set; }
        public Nullable<System.DateTime> LEDGER_DATE_SL { get; set; }
        public string VOUCHERNO_SL { get; set; }
        public string OTHERREF_SL { get; set; }
        public string PRODID_SL { get; set; }
        public string BATCHNO_SL { get; set; }
        public Nullable<decimal> RECEPT_QTY_SL { get; set; }
        public Nullable<decimal> RECEPT_RATE_SL { get; set; }
        public Nullable<decimal> ISSUE_QTY_SL { get; set; }
        public Nullable<decimal> ISSUE_RATE_SL { get; set; }
        public string UNIT_SL { get; set; }
        public string STATUS_SL { get; set; }
    
        public virtual UNITMESSUREMENT UNITMESSUREMENT { get; set; }
    }
}
