//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_REPORT
    {
        public int SLNO_STOCK { get; set; }
        public Nullable<System.DateTime> DATE_STOCK { get; set; }
        public string PRODID_STOCK { get; set; }
        public string PRODDESCRIPTION_STOCK { get; set; }
        public Nullable<int> RECEIPTQTY_STOCK { get; set; }
        public Nullable<decimal> RECEIPTRATE_STOCK { get; set; }
        public Nullable<int> ISSUEQTY_STOCK { get; set; }
        public Nullable<decimal> ISSUERATE_STOCK { get; set; }
        public string UNIT_STOCK { get; set; }
        public string DOCNO_STOCK { get; set; }
    }
}
