//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKLEDGER_REPORT
    {
        public int SLNO_STR { get; set; }
        public Nullable<System.DateTime> GLDDATE_STR { get; set; }
        public string PROCODE_STR { get; set; }
        public string PRODUCTDISTCRIPTION_STR { get; set; }
        public Nullable<decimal> ISSUEQTY_STR { get; set; }
        public Nullable<decimal> ISSUERATE_STR { get; set; }
        public Nullable<decimal> RECEIPTQTY_STR { get; set; }
        public Nullable<decimal> RECEPTRATE_STR { get; set; }
        public Nullable<decimal> CLOSINGQTY_STR { get; set; }
        public string PARTICULARS_STR { get; set; }
        public string UNIT_STR { get; set; }
        public Nullable<int> NO_STR { get; set; }
    }
}
