//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEPHONE_DIRECTORY
    {
        public int SLNO_TD { get; set; }
        public string NAME_TD { get; set; }
        public string ADDRESS_TD { get; set; }
        public string MOB_TD { get; set; }
        public string PHONE_TD { get; set; }
        public string FAX_TD { get; set; }
        public string EMAIL_TD { get; set; }
    }
}
