//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPREPORT
    {
        public int SLNO_RPT { get; set; }
        public string COLUMN1CODE_H { get; set; }
        public string COLUMN1DESCR_H { get; set; }
        public string COUMEN2CODE_H { get; set; }
        public string COLUMN2DESCR_H { get; set; }
        public string COLUMN3CODE_H { get; set; }
        public string COLUMN3DESCR_H { get; set; }
        public string COLUMN4CODE_H { get; set; }
        public string COLUMN4DESCR_H { get; set; }
        public string COLUMN5CODE_H { get; set; }
        public string COLUMN5DESC_H { get; set; }
        public Nullable<System.DateTime> COLUMN1DATE_H { get; set; }
        public Nullable<System.DateTime> COLUMN2DATE_H { get; set; }
        public string COLUMN1CODE_D { get; set; }
        public string COLUMN1DESC_D { get; set; }
        public Nullable<int> COLUMN1QTY_D { get; set; }
        public Nullable<int> COULUMN1RATE_D { get; set; }
        public Nullable<int> COULUMN1AMOUNT_D { get; set; }
        public Nullable<int> COLUMN2QTY_D { get; set; }
        public Nullable<int> COULUMN2RATE_D { get; set; }
        public Nullable<int> COULUMN2AMOUNT_D { get; set; }
        public string TOTALWORDS { get; set; }
    }
}
