//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIALBALANCE
    {
        public int SLN_TB { get; set; }
        public Nullable<int> CODE_TB { get; set; }
        public string ACCODE_TB { get; set; }
        public string DESCRIPTION_TB { get; set; }
        public Nullable<decimal> OPENING_TB { get; set; }
        public Nullable<decimal> DEBIT_TB { get; set; }
        public Nullable<decimal> CREDIT_TB { get; set; }
        public Nullable<decimal> NET_TB { get; set; }
    }
}
