//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITMESSUREMENT
    {
        public UNITMESSUREMENT()
        {
            this.STOCKLEDGERs = new HashSet<STOCKLEDGER>();
        }
    
        public string UNIT_UM { get; set; }
        public string DESCRIPTION_UM { get; set; }
        public string TYPE_UM { get; set; }
        public Nullable<int> UNITQTY_UM { get; set; }
        public string BASICPRIMARYUNIT_UM { get; set; }
        public Nullable<int> BASICPRIMARYQTY_UM { get; set; }
    
        public virtual ICollection<STOCKLEDGER> STOCKLEDGERs { get; set; }
    }
}
