//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERCODE_USER { get; set; }
        public string USERNAME_USER { get; set; }
        public string PASSWORD_USER { get; set; }
        public Nullable<bool> FINANCE_STATUS { get; set; }
        public Nullable<bool> DAYLYTRANSACTION_STATUS { get; set; }
        public Nullable<bool> ADMIN_STATUS { get; set; }
        public Nullable<bool> SETTINGS_STATUS { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
