//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHERCHILD_RPT
    {
        public int SLNO_VCD { get; set; }
        public string ALLCODE_VCD { get; set; }
        public string NARRATION_VCD { get; set; }
        public string ACCODE_VCD { get; set; }
        public string ACDESCRIPTION_VCD { get; set; }
        public Nullable<decimal> DEBITAMOUNT_VCD { get; set; }
        public Nullable<decimal> CREDITAMOUNT_VCD { get; set; }
        public string AMOUNTSTATUTS_VCD { get; set; }
        public string DOCNO_VCD { get; set; }
    }
}
