//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASI.MGC.FS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHERMASTER_RPT
    {
        public int SLNO_VRPT { get; set; }
        public Nullable<System.DateTime> GLDATE_VRPT { get; set; }
        public string ALLCODE_VRPT { get; set; }
        public string BANKCODE_VRT { get; set; }
        public Nullable<decimal> BANKAMOUNT_VRT { get; set; }
        public string ACCDESCRIPTION_VRPT { get; set; }
        public string PARTICULARS_VRPT { get; set; }
        public string NOTES_VRPT { get; set; }
        public Nullable<decimal> DEBITAMOUT_VRPT { get; set; }
        public Nullable<decimal> CREDITAMOUNT_VRPT { get; set; }
        public string STATUS_VRPT { get; set; }
        public string CHQNO_VRPT { get; set; }
        public Nullable<System.DateTime> CHQDATE_VRPT { get; set; }
        public string USER_VRPT { get; set; }
        public string DOCNO_VRPT { get; set; }
        public string VOUCHER_TYPE { get; set; }
        public string DrawerBr_VRPT { get; set; }
        public Nullable<decimal> VAT_VRPT { get; set; }
        public string ACCVATNO_VRPT { get; set; }
    }
}
